apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fljoph0sv-python 
  janus-idp.io/tekton: fljoph0sv-python
  backstage.io/kubernetes-id: fljoph0sv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fljoph0sv-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  